### ISSUE TITLE
[Time] TimeTable 시간표 시각화

### ISSUE THREAD

**Issue by SWARVY** [kgu-clab/clab-platforms#214]
### Describe

타임테이블에 선택한 강의를 시각화하는 기능을 구현합니다

### Tasks

- [ ] 선택된 강의에 대하여 타임테이블에 강의를 시각화하는 기능 구현
- [ ] 디자인 일부 변경
- [ ] 쿼리 파라미터에 데이터를 저장하고, 새로고침시에도 해당 파라미터를 바탕으로 강의를 시각화하는 기능 구현
