### ISSUE TITLE
[Member] 활동 QA 피드백 개선

### ISSUE THREAD

**Issue by Jeong-Ag** [kgu-clab/clab-platforms#220]
### Describe

운영진 대상으로 진행된 활동 QA를 바탕으로 코드를 개선합니다.

### Tasks

- [ ] 주차별 활동 추가 후 `input` 초기화
- [ ] Textarea 제한 글자 수 초과 시 API 요청 막기
- [ ] 스터디 관리`/activity/:id/config`에서 프로필 편집 후에 그룹 페이지`/activity`에 변경 내역 반영되도록 수정
- [ ] 그룹 멤버만 과제 페이지 접근할 수 있도록 권한 설정
- [ ] API 중복 요청 막기
- [ ] 활동 신청 후 그룹 페이지`/activity`로 이동
- [ ] 활동 생성 실패 사유 `toast`로 띄우기
- [ ] 반응형 보완
- [ ] Section Header 클릭 시 해당 페이지로 이동
- [ ] 파일 조회 에러 수정

### ETC

주말에 진행될 두 번째 QA 이후 내용 추가하겠습니다.
