### ISSUE TITLE
[Time] 1차 피드백 반영

### ISSUE THREAD

**Issue by SWARVY** [kgu-clab/clab-platforms#227]
### Describe

1차 피드백 내용들을 반영합니다

### Tasks

- [x] 전공 검색 시 선택한 전공이 남아있도록
- [x] 강의 필터링시 레이아웃 쉬프트 문제 수정
- [ ] `L`, `.5L` 교시 보여주는 옵션을 선택적으로 조정
- [ ] 주 / 야간 변경시 선택된 강의를 초기화 하는것이 아니라 데이터를 저장하고 있도록 변경
- [ ] 시간표를 이미지 다운로드 할 수 있도록 구현
- [x] 강의 삭제 모달 사이즈가 비정상적인점 수정
- [ ] 강의 테이블 사이즈 고정 (가능하다면)
- [ ] 총 학점을 보여주는 기능 구현
- [ ] `alert`를 `toast`로 변경하여 출력
