### ISSUE TITLE
[Member] 활동 2차 QA 피드백 개선

### ISSUE THREAD

**Issue by Jeong-Ag** [kgu-clab/clab-platforms#229]
### Describe

운영진 대상으로 진행된 활동 QA를 바탕으로 코드를 개선합니다.

### Tasks

- [x] 과제 첫 제출 시 파일 업로드 안 됨
- [x] 과제 제출 후 제출된 모습 나타나도록 업데이트
- [x] 과제 제출 시에 파일이나 과제물 설명 중 하나만 충족되어도 제출 가능하도록 변경
- [x] 과제 설명에 종료 일자 및 수정 기능 추가
- [x] 활동 생성 시에 이미지 검색 불가 문제 해결
- [x] 공지사항, 과제 제출, 과제, 주차별 활동에 다중 파일 업로드 기능 추가
- [x] 활동 생성 시 글자수 제한 (제목 30자, 커리큘럼/내용 1000자)
- [x] 캘린더 D-day 계산 표시 문제 개선
- [x] 활동 내용 줄바꿈 문자 처리
- [x] 공지사항 클릭 시 제목 및 파일 확인 추가
- [x] 활동 그룹 멤버 승인 시 멤버 선택 후 일괄 승인 기능 추가
- [x] 활동 그룹 멤버 역할 변경 `Select`에서 `Button` 형식으로 수정
- [x] 활동 그룹, 멤버 상태 변경 시 확인 `modal` 추가
- [x] 활동 그룹 멤버가 아닌 경우 업로드 된 파일 조회 불가 처리

### ETC

Notion에 업데이트 된 피드백 내용을 바탕으로 정리하였습니다.
