### ISSUE TITLE
[RFC]: 멤버스 기능 추가 구현

### ISSUE THREAD

**Issue by SWARVY** [kgu-clab/clab-platforms#230]
### Describe

현 멤버스 시스템에 추가되어야 하거나 누락된 기능에 대하여 기능 개발을 수행합니다.

### Tasks

- [x] 메일 오기입시 사용자 이메일에 다시 메일을 전송하는기능 (관리페이지)
   - #246 
- [ ] 마이페이지에서 수정할 수 있는 정보 추가 (생일, 전화번호 등..)
- [x] 관리페이지 회원 가입시 input에 required 여부 표현하기
  - #237  
- [x] 관리페이지에 사이드 TOC 추가
  - #248
