### ISSUE TITLE
[Member] 3차 QA 피드백 개선

### ISSUE THREAD

**Issue by Jeong-Ag** [kgu-clab/clab-platforms#236]
### Describe

운영진 대상으로 진행된 활동 QA를 바탕으로 코드를 개선합니다.

### Tasks

- [x] 업로드 파일 이미지 조회 에러
- [x] 참여자 없는 경우 멤버 승인 버튼 삭제, 선택 인원 없는 경우에 멤버 승인 버튼 클릭하면 에러 메세지
- [x] 종료되거나 삭제된 활동인 경우 활동 상세 페이지 접근 막기
- [x] 공지사항 파일 추가 후 첨부파일 초기화
- [x] 공지사항, 주차별 활동, 과제 추가의 미리보기에 첨부파일도 나타나도록 수정
- [x] 주차별 활동 추가 시 내용 글자수 제한 수정
- [x] 과제 제출 마감기한이 현재 시간 이전인 경우 에러 메세지
- [x] 스터디 승인/거절 시 모달창에 해당 스터디 정보 나타내기
- [x] 모달창 멘트 수정
- [x] 늦게 제출한 과제에 늦은 시간 표시 
- [x] 활동 그룹 정보에 나타나는 category 한글로 변환
- [x] safari에서 `GroupCard` 이미지 깨지는 경우 개선
