### ISSUE TITLE
[Member] 활동 페이지, 지원 페이지 오류 수정

### ISSUE THREAD

**Issue by Jeong-Ag** [kgu-clab/clab-platforms#252]
### Describe

활동 페이지와 지원 페이지 내부에 있는 오류들을 수정합니다.

### Tasks

- [x] 활동 신청자 조회 페이지네이션 수정
- [x] 과제 제출 인원 조회 오류 수정
- [x] 지원 페이지 내 데이터 리스트 조회 문제 수정
- [x] 활동, 동아리 지원서 html 엔티티 변환
