### ISSUE TITLE
[Feature]: 모의 수강신청 페이지 개발

### ISSUE THREAD

**Issue by Jeong-Ag** [kgu-clab/clab-platforms#256]
### Describe

경기대학교 수강신청 시스템을 바탕으로 한 모의 수강신청 시스템을 개발합니다. 수강 시간표 조회와 같이 수강신청 과정에 불필요한 기능들은 구현하지 않을 예정입니다. 시작 로그인 기능을 제외하고 수강신청 과정에 필요한 기능만 구현하되, 사이트에 접속했을 때의 유사성을 위해 레이아웃과 텍스트는 동일하게 구현합니다.

### Tasks

- [ ] 수강신청 시스템 로그인 후 메인 페이지
- [ ] 과목 리스트 조회
- [ ] 소망가방을 사용한 수강신청 과정
- [ ] 소망가방이 사용하지 않는 경우의 수강신청 과정

### ETC

우선 간략하게 작성하여 이슈 생성했으며 이후 더 세분화할 예정입니다. 12월 초까지 작업 완료가 목표입니다. 🙌
